//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectoWorkSpace.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConectoWorkSpace.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Параметры-AppPlay&gt;
        ///&lt;FileConfig FileConfig_Ver-File-Config=&quot;0_1&quot; /&gt;
        /// &lt;idAppOverall_121 idApp=&quot;121&quot; NameApp=&quot;OtherWork &quot; CaptionNamePlay=&quot;мегоплан&quot; PuthFileIm=&quot;/Conecto®%20WorkSpace;component/Images/ico_prog_megaplan2.png&quot; infoWorkSpace=&quot;true&quot;/&gt;
        ///  &lt;idAppPanelWorkSpace_121 idApp=&quot;121&quot; LinkPanel=&quot;false&quot; TypeLink=&quot;1&quot; NumberPanel=&quot;22&quot; CaptionNameWorkSpace=&quot;Мегоплан&quot; AppStartMetod=&quot;ConectoWorkSpace.AppforWorkSpace.LoadAppEvents_121&quot; TypeApp=&quot;Integer&quot;  AutostartTimeSec=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string appplay {
            get {
                return ResourceManager.GetString("appplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Параметры-AppPlayInstall&gt;
        ///&lt;FileConfig FileConfig_Ver-File-Config=&quot;0.1&quot; /&gt;
        /// &lt;idAppOverall_121 idApp=&quot;121&quot; NameApp=&quot;megoplan&quot; CaptionNamePlay=&quot;мегоплан&quot; PuthFileIm=&quot;/Conecto®%20WorkSpace;component/Images/ico_prog_megaplan1.png&quot; infoWorkSpace=&quot;true&quot;/&gt;
        ///  &lt;idAppPanelWorkSpace_121 idApp=&quot;121&quot; LinkPanel=&quot;true&quot; TypeLink=&quot;1&quot; NumberPanel=&quot;2&quot; CaptionNameWorkSpace=&quot;Мегоплан&quot;/&gt;
        /// &lt;idAppOverall_122 idApp=&quot;122&quot; NameApp=&quot;1crouter&quot; AutorizeType=&quot;0&quot; CaptionNamePlay=&quot;1c шлюз&quot; PuthF [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string configinstallapp {
            get {
                return ResourceManager.GetString("configinstallapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-ru_text,_your_local_text
        ///Ошибка
        ///Информация
        ///Выполняется
        ///Запуск приложения
        ///Отладка
        ///Дата
        ///Каталог песен
        ///Тип сообщения
        ///Сообщение
        ///Отсутствует файл.
        /// </summary>
        internal static string culture_ru_ru_csv {
            get {
                return ResourceManager.GetString("culture_ru_ru_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///(select first 1 f1.id from FISC_JOURNAL f1 where f1.oper=&apos;Z&apos;
        ///and CASH_PRINT_TIME&lt;=f1.OPER_TIME order by oper_time) as id_z,
        ///(select first 1 f1.oper_time from FISC_JOURNAL f1 where f1.oper=&apos;Z&apos;
        ///and CASH_PRINT_TIME&lt;=f1.OPER_TIME order by oper_time) as z_opertime,
        ///CASH_PRINT_TIME,
        ///dat,
        ///num,
        ///PODR_KOD as podr ,
        ///(select name from spr_podr p where p.kod=PODR_KOD ) as podr_name ,
        ///(select p.org from spr_podr p where p.kod=PODR_KOD) as org_our,
        ///(select o.name from spr_podr p, spr_org o where o.kod=p. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string import_act_realiz_sql_fb {
            get {
                return ResourceManager.GetString("import_act_realiz_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select hd.dat,hd.num, hd.podr ,
        ///(select name from  spr_podr p where p.kod=hd.PODR ) as podr_name ,
        ///(select p.org from spr_podr p where  p.kod=hd.podr) as org_our,
        ///(select o.name from spr_podr p, spr_org o where o.kod=p.org and p.kod=hd.podr) as org_our_name,
        ///rc.TOV, (select name from spr_tov where kod=tov) as tov_name,
        /// rc.DOP_CNT as cnt, rc.DOP_PRICE as priceNds, 
        ///rc.SUMMA as summaNds, hd.nds,
        /// hd.ORG, (select name from spr_org where hd.org=kod) as org_name,
        /// hd.type_doc,  (case hd.TYPE_DOC  when 8 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string import_act_spis_sql_fb {
            get {
                return ResourceManager.GetString("import_act_spis_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select hd.POST, hd.PODR, hd.DAT, hd.NUM, hd.SUMMA,hd.TYPE_NDS, hd.NDS,  hd.SOTR,
        /// hd.TYPE_DOC, hd.TYPE_PRICE, hd.DOC_STATE, hd.ORG_FROM,  hd.TIME_OPEN,   hd.WHITE,
        /// rc.TOV, rc.CNT, rc.DOP_CNT, rc.ED, rc.ED_NAME, rc.PRICE, rc.DOP_PRICE, rc.SUMMA, rc.ORIGIN_PRICE, 
        /// hd.PRIM  
        /// from MN_HD_TOV_MOVE hd, mn_rc_tov_move rc 
        /// where rc.doc=hd.KOD  
        /// and (hd.dat between &apos;{0}&apos; and &apos;{1}&apos;)
        /// and (&apos;{2}&apos;=&apos;0&apos; or CHECKKODENTRY(hd.podr,&apos;{2}&apos;)&gt;0)
        /// order by hd.dat.
        /// </summary>
        internal static string import_peremech_prod_sql_fb {
            get {
                return ResourceManager.GetString("import_peremech_prod_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select hd.dat,hd.num,  hd.podr ,
        ///(select name from  spr_podr p where p.kod=hd.PODR ) as podr_name ,
        ///(select p.org from spr_podr p where  p.kod=hd.podr) as org_our,
        ///(select o.name from spr_podr p, spr_org o where o.kod=p.org and p.kod=hd.podr) as org_our_name,
        ///rc.TOV, (select name from spr_tov where kod=tov) as tov_name,
        /// rc.DOP_CNT as cnt, rc.DOP_PRICE as priceNds, 
        /// rc.SUMMA as summaNds, hd.nds,
        /// hd.post, (select name from spr_org where hd.post=kod) as org_name,
        ///(case rc.ED_NAME    when &apos;кг&apos; then 1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string import_ptsk_sql_fb {
            get {
                return ResourceManager.GetString("import_ptsk_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select
        ///a.DAT,a.KOD_GROUP,org,a.NAME_GROUP,sum(a.SUM_NAL) as SUM_NAL, sum(a.SUM_VISA) as sum_visa, sum(a.SUM_BNAL) as sum_bnal,
        ///COALESCE((select name from spr_org where org=kod),&apos;&apos;) as org_name
        ///  from ALT_HT_PRC_RP_OBS_GRP_1C(&apos;{0}&apos;,&apos;{1}&apos;,0) a
        ///group by a.KOD_GROUP,a.NAME_GROUP,a.dat,org
        ///order by a.dat,a.NAME_GROUP
        ///
        ///
        ///.
        /// </summary>
        internal static string import_stv_oborot_otel_sql_fb {
            get {
                return ResourceManager.GetString("import_stv_oborot_otel_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на select t.kod, t.name,(case ed  when &apos;кг&apos; then 1   when &apos;л&apos; then 2   when &apos;порц&apos; then 3   when &apos;гр&apos; then 4   when &apos;мл&apos; then 5   when &apos;бут&apos; then 6 else 10 end) as edId,
        /// t.ed from spr_tov t
        ///where  not exists (select kod from mn_hd_norm hd where tov=t.KOD) and
        ///exists (select g.kod from  spr_group g where g.kod=t.grp and g.podr in({2}) ) and
        ///ed&lt;&gt;&apos;-&apos;  and (POSITION(ed in &apos;порц&apos;)=0) and substr(name,1,1)&lt;&gt;&apos; &apos;
        ///order by name
        ///
        ///
        ///.
        /// </summary>
        internal static string import_stv_sql_fb {
            get {
                return ResourceManager.GetString("import_stv_sql_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;Параметры-Servers&gt;
        ///&lt;FileConfig FileConfig_Ver-File-Config=&quot;0_1&quot; /&gt;
        ///  &lt;idServersOverall_10 id=&quot;10&quot; NameServers=&quot;Karaoke&quot; CaptionName=&quot;Караоке Бар&quot; Version=&quot;0.01&quot; StartMetod=&quot;ConectoWorkSpace.KaraokeServer.StartKaraoke&quot;  AutoStatrt=&quot;false&quot; TypeServer=&quot;Integer&quot; PuthFileIm=&quot;/Conecto®%20WorkSpace;component/Images/ico_prog_megaplan1.png&quot; /&gt;
        ///  &lt;idServersOverall_10_Network TCP-MOBILE-UNIVERSAL-I=&quot;50700&quot; CountRowDataSendDevice=&quot;100&quot; NameKaraokeShop=&quot;ДомВкуса&quot; DebugInfo=&quot;t [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string servers {
            get {
                return ResourceManager.GetString("servers", resourceCulture);
            }
        }
    }
}
